# Site settings
title: Jeremy Guillette
header-img: img/horizon.png
email: me@jaguillette.com
description: "This is my personal site, enjoy!"
#baseurl: "/jaguillette.github.io"
url: "http://jeremyguillette.com"
twitter_username: jaxguillette
github_username:  jaguillette
linkedin_username:  jaguillette
#facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
