# Site settings
title: Jeremy Guillette
header-img: img/home-bg.jpg
email: me@jaguillette.com
description: "This is my personal site, enjoy!"
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://jeremyguillette.com"
twitter_username: @jaguillette
github_username:  jaguillette
#facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
